M48
; DRILL file {KiCad (7.0.0-0)} date Monday, May 06, 2024 at 05:20:08 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-06T17:20:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X8.2543Y-2.2354
X8.2543Y-2.826
T2
X6.0921Y-5.3043
X6.6921Y-3.3043
X7.7921Y-3.3043
X7.9921Y-5.3543
T0
M30
